In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4657 entries, 0 to 4656
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    4657 non-null   int64
 1   title    4657 non-null   str
 2   genre    4657 non-null   str
 3   summary  4657 non-null   str
dtypes: int64(1), str(3)
memory usage: 9.6 MB

In [4]:
df.duplicated().value_counts()

False    4657
Name: count, dtype: int64

In [5]:
df

,index,title,genre,summary
0,0,Drowned Wednesday,fantasy,Drowned Wednesday is the first Trustee among ...
1,1,The Lost Hero,fantasy,"As the book opens, Jason awakens on a school ..."
2,2,The Eyes of the Overworld,fantasy,Cugel is easily persuaded by the merchant Fia...
3,3,Magic's Promise,fantasy,The book opens with Herald-Mage Vanyel return...
4,4,Taran Wanderer,fantasy,Taran and Gurgi have returned to Caer Dallben...
...,...,...,...,...
4652,4652,Hounded,fantasy,"Atticus O’Sullivan, last of the Druids, lives ..."
4653,4653,Charlie and the Chocolate Factory,fantasy,Charlie Bucket's wonderful adventure begins wh...
4654,4654,Red Rising,fantasy,"""I live for the dream that my children will be..."
4655,4655,Frostbite,fantasy,"Rose loves Dimitri, Dimitri might love Tasha, ..."
4656,4656,Radiance,fantasy,"The Prince of no value\nBrishen Khaskem, princ..."

In [6]:
df['genre'].unique()

<ArrowStringArray>
[   'fantasy',    'science',      'crime',    'history',     'horror',
   'thriller', 'psychology',    'romance',     'sports',     'travel']
Length: 10, dtype: str

In [7]:
df['title'].duplicated().value_counts()

title
False    4296
True      361
Name: count, dtype: int64

In [8]:
df=df.drop_duplicates(subset='title',keep='first')

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 4296 entries, 0 to 4656
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    4296 non-null   int64
 1   title    4296 non-null   str
 2   genre    4296 non-null   str
 3   summary  4296 non-null   str
dtypes: int64(1), str(3)
memory usage: 9.3 MB

In [10]:
df['title'].duplicated().value_counts()

title
False    4296
Name: count, dtype: int64

In [11]:
df['tags'] = df['genre'] + " " + df['summary']
df[['title', 'tags']].head()

,title,tags
0,Drowned Wednesday,fantasy Drowned Wednesday is the first Truste...
1,The Lost Hero,"fantasy As the book opens, Jason awakens on a..."
2,The Eyes of the Overworld,fantasy Cugel is easily persuaded by the merc...
3,Magic's Promise,fantasy The book opens with Herald-Mage Vanye...
4,Taran Wanderer,fantasy Taran and Gurgi have returned to Caer...

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 4296 entries, 0 to 4656
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    4296 non-null   int64
 1   title    4296 non-null   str
 2   genre    4296 non-null   str
 3   summary  4296 non-null   str
 4   tags     4296 non-null   str
dtypes: int64(1), str(4)
memory usage: 18.4 MB

In [15]:
df = df[['index', 'title', 'tags']]
df.info()

<class 'pandas.DataFrame'>
Index: 4296 entries, 0 to 4656
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   4296 non-null   int64
 1   title   4296 non-null   str
 2   tags    4296 non-null   str
dtypes: int64(1), str(2)
memory usage: 9.3 MB

In [16]:
df

,index,title,tags
0,0,Drowned Wednesday,fantasy Drowned Wednesday is the first Truste...
1,1,The Lost Hero,"fantasy As the book opens, Jason awakens on a..."
2,2,The Eyes of the Overworld,fantasy Cugel is easily persuaded by the merc...
3,3,Magic's Promise,fantasy The book opens with Herald-Mage Vanye...
4,4,Taran Wanderer,fantasy Taran and Gurgi have returned to Caer...
...,...,...,...
4651,4651,Fantastic Beasts and Where to Find Them: The O...,fantasy J.K. Rowling's screenwriting debut is ...
4652,4652,Hounded,"fantasy Atticus O’Sullivan, last of the Druids..."
4653,4653,Charlie and the Chocolate Factory,fantasy Charlie Bucket's wonderful adventure b...
4654,4654,Red Rising,"fantasy ""I live for the dream that my children..."
4656,4656,Radiance,fantasy The Prince of no value\nBrishen Khaske...

In [17]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

def stem_text(text):
    words = text.split()

    stemmed_words = []

    for word in words:
        stemmed_words.append(ps.stem(word))

    return " ".join(stemmed_words)

In [18]:
df['tags'] = df['tags'].str.lower()

In [19]:
df['tags']=df['tags'].apply(stem_text)

In [20]:
#df.head()

In [21]:
df.to_csv("clean_data_books.csv",index=False)